package com.yuangee.flower.customer.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yuangee.flower.customer.entity.Address;
import com.yuangee.flower.customer.entity.AuctionTime;
import com.yuangee.flower.customer.entity.BusinessTime;
import com.yuangee.flower.customer.entity.Coupon;
import com.yuangee.flower.customer.entity.DestineTime;
import com.yuangee.flower.customer.entity.Express;
import com.yuangee.flower.customer.entity.Genre;
import com.yuangee.flower.customer.entity.GenreSub;
import com.yuangee.flower.customer.entity.Member;
import com.yuangee.flower.customer.entity.MemberToken;
import com.yuangee.flower.customer.entity.Shop;
import com.yuangee.flower.customer.entity.UpdateWares;

import com.yuangee.flower.customer.db.AddressDao;
import com.yuangee.flower.customer.db.AuctionTimeDao;
import com.yuangee.flower.customer.db.BusinessTimeDao;
import com.yuangee.flower.customer.db.CouponDao;
import com.yuangee.flower.customer.db.DestineTimeDao;
import com.yuangee.flower.customer.db.ExpressDao;
import com.yuangee.flower.customer.db.GenreDao;
import com.yuangee.flower.customer.db.GenreSubDao;
import com.yuangee.flower.customer.db.MemberDao;
import com.yuangee.flower.customer.db.MemberTokenDao;
import com.yuangee.flower.customer.db.ShopDao;
import com.yuangee.flower.customer.db.UpdateWaresDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig addressDaoConfig;
    private final DaoConfig auctionTimeDaoConfig;
    private final DaoConfig businessTimeDaoConfig;
    private final DaoConfig couponDaoConfig;
    private final DaoConfig destineTimeDaoConfig;
    private final DaoConfig expressDaoConfig;
    private final DaoConfig genreDaoConfig;
    private final DaoConfig genreSubDaoConfig;
    private final DaoConfig memberDaoConfig;
    private final DaoConfig memberTokenDaoConfig;
    private final DaoConfig shopDaoConfig;
    private final DaoConfig updateWaresDaoConfig;

    private final AddressDao addressDao;
    private final AuctionTimeDao auctionTimeDao;
    private final BusinessTimeDao businessTimeDao;
    private final CouponDao couponDao;
    private final DestineTimeDao destineTimeDao;
    private final ExpressDao expressDao;
    private final GenreDao genreDao;
    private final GenreSubDao genreSubDao;
    private final MemberDao memberDao;
    private final MemberTokenDao memberTokenDao;
    private final ShopDao shopDao;
    private final UpdateWaresDao updateWaresDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        addressDaoConfig = daoConfigMap.get(AddressDao.class).clone();
        addressDaoConfig.initIdentityScope(type);

        auctionTimeDaoConfig = daoConfigMap.get(AuctionTimeDao.class).clone();
        auctionTimeDaoConfig.initIdentityScope(type);

        businessTimeDaoConfig = daoConfigMap.get(BusinessTimeDao.class).clone();
        businessTimeDaoConfig.initIdentityScope(type);

        couponDaoConfig = daoConfigMap.get(CouponDao.class).clone();
        couponDaoConfig.initIdentityScope(type);

        destineTimeDaoConfig = daoConfigMap.get(DestineTimeDao.class).clone();
        destineTimeDaoConfig.initIdentityScope(type);

        expressDaoConfig = daoConfigMap.get(ExpressDao.class).clone();
        expressDaoConfig.initIdentityScope(type);

        genreDaoConfig = daoConfigMap.get(GenreDao.class).clone();
        genreDaoConfig.initIdentityScope(type);

        genreSubDaoConfig = daoConfigMap.get(GenreSubDao.class).clone();
        genreSubDaoConfig.initIdentityScope(type);

        memberDaoConfig = daoConfigMap.get(MemberDao.class).clone();
        memberDaoConfig.initIdentityScope(type);

        memberTokenDaoConfig = daoConfigMap.get(MemberTokenDao.class).clone();
        memberTokenDaoConfig.initIdentityScope(type);

        shopDaoConfig = daoConfigMap.get(ShopDao.class).clone();
        shopDaoConfig.initIdentityScope(type);

        updateWaresDaoConfig = daoConfigMap.get(UpdateWaresDao.class).clone();
        updateWaresDaoConfig.initIdentityScope(type);

        addressDao = new AddressDao(addressDaoConfig, this);
        auctionTimeDao = new AuctionTimeDao(auctionTimeDaoConfig, this);
        businessTimeDao = new BusinessTimeDao(businessTimeDaoConfig, this);
        couponDao = new CouponDao(couponDaoConfig, this);
        destineTimeDao = new DestineTimeDao(destineTimeDaoConfig, this);
        expressDao = new ExpressDao(expressDaoConfig, this);
        genreDao = new GenreDao(genreDaoConfig, this);
        genreSubDao = new GenreSubDao(genreSubDaoConfig, this);
        memberDao = new MemberDao(memberDaoConfig, this);
        memberTokenDao = new MemberTokenDao(memberTokenDaoConfig, this);
        shopDao = new ShopDao(shopDaoConfig, this);
        updateWaresDao = new UpdateWaresDao(updateWaresDaoConfig, this);

        registerDao(Address.class, addressDao);
        registerDao(AuctionTime.class, auctionTimeDao);
        registerDao(BusinessTime.class, businessTimeDao);
        registerDao(Coupon.class, couponDao);
        registerDao(DestineTime.class, destineTimeDao);
        registerDao(Express.class, expressDao);
        registerDao(Genre.class, genreDao);
        registerDao(GenreSub.class, genreSubDao);
        registerDao(Member.class, memberDao);
        registerDao(MemberToken.class, memberTokenDao);
        registerDao(Shop.class, shopDao);
        registerDao(UpdateWares.class, updateWaresDao);
    }
    
    public void clear() {
        addressDaoConfig.clearIdentityScope();
        auctionTimeDaoConfig.clearIdentityScope();
        businessTimeDaoConfig.clearIdentityScope();
        couponDaoConfig.clearIdentityScope();
        destineTimeDaoConfig.clearIdentityScope();
        expressDaoConfig.clearIdentityScope();
        genreDaoConfig.clearIdentityScope();
        genreSubDaoConfig.clearIdentityScope();
        memberDaoConfig.clearIdentityScope();
        memberTokenDaoConfig.clearIdentityScope();
        shopDaoConfig.clearIdentityScope();
        updateWaresDaoConfig.clearIdentityScope();
    }

    public AddressDao getAddressDao() {
        return addressDao;
    }

    public AuctionTimeDao getAuctionTimeDao() {
        return auctionTimeDao;
    }

    public BusinessTimeDao getBusinessTimeDao() {
        return businessTimeDao;
    }

    public CouponDao getCouponDao() {
        return couponDao;
    }

    public DestineTimeDao getDestineTimeDao() {
        return destineTimeDao;
    }

    public ExpressDao getExpressDao() {
        return expressDao;
    }

    public GenreDao getGenreDao() {
        return genreDao;
    }

    public GenreSubDao getGenreSubDao() {
        return genreSubDao;
    }

    public MemberDao getMemberDao() {
        return memberDao;
    }

    public MemberTokenDao getMemberTokenDao() {
        return memberTokenDao;
    }

    public ShopDao getShopDao() {
        return shopDao;
    }

    public UpdateWaresDao getUpdateWaresDao() {
        return updateWaresDao;
    }

}
