package com.yuangee.flower.customer.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yuangee.flower.customer.entity.Express;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EXPRESS".
*/
public class ExpressDao extends AbstractDao<Express, Long> {

    public static final String TABLENAME = "EXPRESS";

    /**
     * Properties of entity Express.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property ExpressDeliveryName = new Property(1, String.class, "expressDeliveryName", false, "EXPRESS_DELIVERY_NAME");
        public final static Property ExpressDeliveryMoney = new Property(2, double.class, "expressDeliveryMoney", false, "EXPRESS_DELIVERY_MONEY");
    }


    public ExpressDao(DaoConfig config) {
        super(config);
    }
    
    public ExpressDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EXPRESS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"EXPRESS_DELIVERY_NAME\" TEXT," + // 1: expressDeliveryName
                "\"EXPRESS_DELIVERY_MONEY\" REAL NOT NULL );"); // 2: expressDeliveryMoney
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EXPRESS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Express entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String expressDeliveryName = entity.getExpressDeliveryName();
        if (expressDeliveryName != null) {
            stmt.bindString(2, expressDeliveryName);
        }
        stmt.bindDouble(3, entity.getExpressDeliveryMoney());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Express entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String expressDeliveryName = entity.getExpressDeliveryName();
        if (expressDeliveryName != null) {
            stmt.bindString(2, expressDeliveryName);
        }
        stmt.bindDouble(3, entity.getExpressDeliveryMoney());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public Express readEntity(Cursor cursor, int offset) {
        Express entity = new Express( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // expressDeliveryName
            cursor.getDouble(offset + 2) // expressDeliveryMoney
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Express entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setExpressDeliveryName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setExpressDeliveryMoney(cursor.getDouble(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Express entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Express entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Express entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
